import { HotelAmenities } from 'src/enums/hotels'
import {
  mdiWifi,
  mdiSilverwareForkKnife,
  mdiRoomService,
  mdiGlassMugVariant,
  mdiPool,
  mdiDog,
  mdiParking,
  mdiCoffee,
  mdiHotTub,
  mdiTumbleDryer,
  mdiDumbbell,
  mdiSeatOutline,
  mdiAirFilter,
  mdiSafe,
  mdiTelevision,
  mdiHours24,
  mdiMicrophone,
  mdiTheater,
  mdiSpa,
} from '@mdi/js'

export const amenitiesIcons: Record<HotelAmenities, string> = {
  [HotelAmenities.WIFI]: mdiWifi,
  [HotelAmenities.RESTAURANT]: mdiSilverwareForkKnife,
  [HotelAmenities.ROOM_SERVICE]: mdiRoomService,
  [HotelAmenities.PUB]: mdiGlassMugVariant,
  [HotelAmenities.POOL]: mdiPool,
  [HotelAmenities.PETS]: mdiDog,
  [HotelAmenities.BREAKFAST]: mdiCoffee,
  [HotelAmenities.PARKING]: mdiParking,
  [HotelAmenities.LAUNDRY]: mdiTumbleDryer,
  [HotelAmenities.FITNESS_CENTER]: mdiDumbbell,
  [HotelAmenities.MEETING_ROOM]: mdiSeatOutline,
  [HotelAmenities.STEAM_ROOM]: mdiHotTub,
  [HotelAmenities.AIR_CONDITIONING]: mdiAirFilter,
  [HotelAmenities.SAFE]: mdiSafe,
  [HotelAmenities.ROOM_TV]: mdiTelevision,
  [HotelAmenities.RECEPTION_24_HOURS]: mdiHours24,
  [HotelAmenities.AUDITORIUM]: mdiMicrophone,
  [HotelAmenities.STAGE]: mdiTheater,
  [HotelAmenities.SPA]: mdiSpa,
}
